Date: 01-10-2024 15:01:03
Exception: An employee with the name 'Raj15' already exists.
Stack Trace:    at ExceptionHandlingDemo.Controllers.EmployeeController.Create(Employee employee) in C:\Users\Admin\source\repos\ExceptionHandlingDemo\ExceptionHandlingDemo\Controllers\EmployeeController.cs:line 44
-----------------------------------
Date: 01-10-2024 15:04:39
Exception: An employee with the name 'Raj15' already exists.
Stack Trace:    at ExceptionHandlingDemo.Controllers.EmployeeController.Create(Employee employee) in C:\Users\Admin\source\repos\ExceptionHandlingDemo\ExceptionHandlingDemo\Controllers\EmployeeController.cs:line 44
-----------------------------------
Date: 01-10-2024 16:05:58
Exception: An employee with the name 'Raj15' already exists.
Stack Trace:    at ExceptionHandlingDemo.Controllers.EmployeeController.Create(Employee employee) in C:\Users\Admin\source\repos\ExceptionHandlingDemo\ExceptionHandlingDemo\Controllers\EmployeeController.cs:line 42
   at lambda_method58(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at ExceptionHandlingDemo.Middlewares.ExceptionHandlingMiddleware.InvokeAsync(HttpContext context) in C:\Users\Admin\source\repos\ExceptionHandlingDemo\ExceptionHandlingDemo\Middlewares\ExceptionHandlingMiddleware.cs:line 23
-----------------------------------
